---
- hosts: all
  vars_files:
    - vars/default.yml

  pre_tasks:
    - name: Install prerequisites
      apt: name=aptitude update_cache=yes state=latest force_apt_get=yes
      become: true
      tags: [ system ]

- name: Устанавливаем стек LAMP и WordPress на Debian
  hosts: myhosts
  become: yes
  vars_files:
    - roles/mysql/vars/main.yml
    - roles/wordpress/vars/main.yml
  roles:
    - common
    - apache
    - mysql
    - php
    - wordpress
