---
- name: Обновление apt и установка базовых пакетов
  apt:
    update_cache: yes
    cache_valid_time: 3600

- name: Установка Python и зависимостей
  apt:
    name:
      - python3
      - python3-mysqldb
      - unzip
    state: present